// <auto-generated />
using System;
using BetPlay.Infrastructure.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BetPlay.Infrastructure.EfCore.Migrations
{
    [DbContext(typeof(BetPlayDbContext))]
    partial class BetPlayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("BetPlay.Domain.TrackedLeague", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TrackedLeagues");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4daa1f88-7014-4c71-b6eb-571fd5a50339"),
                            LeagueId = 78,
                            LogoUrl = "https://media.api-sports.io/football/leagues/78.png",
                            Name = "Bundesliga"
                        },
                        new
                        {
                            Id = new Guid("2c264547-fad4-4aea-ae50-d0c6435cfaf0"),
                            LeagueId = 39,
                            LogoUrl = "https://media.api-sports.io/football/leagues/39.png",
                            Name = "Premier League"
                        },
                        new
                        {
                            Id = new Guid("a5b09102-c436-435a-9ba6-e61cb83245ed"),
                            LeagueId = 140,
                            LogoUrl = "https://media.api-sports.io/football/leagues/140.png",
                            Name = "La Liga"
                        },
                        new
                        {
                            Id = new Guid("9ae9c8c7-2c39-476e-910c-c3adb7d8b625"),
                            LeagueId = 135,
                            LogoUrl = "https://media.api-sports.io/football/leagues/135.png",
                            Name = "Serie A"
                        },
                        new
                        {
                            Id = new Guid("63c8d11e-7e2f-4bc5-8041-ab06cc0c6290"),
                            LeagueId = 61,
                            LogoUrl = "https://media.api-sports.io/football/leagues/61.png",
                            Name = "Ligue 1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
